<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>LTC.PaymentService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LTC.PaymentService.Domain\LTC.PaymentService.Domain.csproj" />
    <ProjectReference Include="..\LTC.PaymentService.TestBase\LTC.PaymentService.TestBase.csproj" />
  </ItemGroup>

</Project>
